#!/usr/bin/env bash
set -euo pipefail

home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/..)"

echo 'updating options for typesetting'
coffee --map -o lib -c options.coffee
cd ../mingkwai-ncr
node lib/main.js


