// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var $, $async, CND, D, ECS, MD_READER, MKTS, alert, badge, copy, debug, echo, help, hide, info, is_hidden, is_stamped, log, rpr, select, stamp, unstamp, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MKTS/TABLE';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  D = require('pipedreams');

  $ = D.remit.bind(D);

  $async = D.remit_async.bind(D);

  //...........................................................................................................
  ECS = require('./eval-cs');

  MKTS = require('./main');

  MD_READER = require('./md-reader');

  hide = MD_READER.hide.bind(MD_READER);

  copy = MD_READER.copy.bind(MD_READER);

  stamp = MD_READER.stamp.bind(MD_READER);

  unstamp = MD_READER.unstamp.bind(MD_READER);

  select = MD_READER.select.bind(MD_READER);

  is_hidden = MD_READER.is_hidden.bind(MD_READER);

  is_stamped = MD_READER.is_stamped.bind(MD_READER);

  //...........................................................................................................
  copy = function(x) {
    return Object.assign({}, x);
  };

  //-----------------------------------------------------------------------------------------------------------
  this.new_description = function(S) {
    var R;
    R = {
      '~isa': 'MKTS/TABLE/description',
      grid: {
        width: 4,
        height: 4
      },
      /* default unit for width, height: */
      u: {
        width: '10mm',
        height: '10mm'
      },
      cells: []
    };
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.grid = function(me, t) {
    var _, col_count_txt, match, row_count_txt, type;
    //.........................................................................................................
    if ((type = CND.type_of(t)) !== 'text') {
      throw new Error(`(MKTS/TABLE 5183) need a text for mkts-table/grid, got a ${type}`);
    }
    if ((match = t.match(/^(\d+)\s*x(\d+)$/)) == null) {
      throw new Error(`(MKTS/TABLE 7414) need a text like '3 x 4' or similar for mkts-table/grid, got ${rpr(t)}`);
    }
    //.........................................................................................................
    [_, col_count_txt, row_count_txt] = match;
    me.grid.width = parseInt(col_count_txt, 10);
    me.grid.height = parseInt(row_count_txt, 10);
    //.........................................................................................................
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.merge = function(me, text) {
    var type;
    //.........................................................................................................
    if ((type = CND.type_of(text)) !== 'text') {
      throw new Error(`(MKTS/TABLE 3075) need a text for mkts-table/merge, got a ${type}`);
    }
    //.........................................................................................................
    me.cells.push(this.parse_merge_quadref(text));
    //.........................................................................................................
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._idx_from_col_and_row = function(col, row) {
    var col_idx, row_idx, type;
    if ((type = CND.type_of(col)) !== 'text') {
      throw new Error(`(MKTS/TABLE 4726) expected a text for col, got a ${rpr(type)}`);
    }
    if ((type = CND.type_of(row)) !== 'text') {
      throw new Error(`(MKTS/TABLE 8186) expected a text for row, got a ${rpr(type)}`);
    }
    col_idx = (col.codePointAt(0)) - ('a'.codePointAt(0));
    row_idx = (parseInt(row, 10)) - 1;
    return {
      col: col_idx,
      row: row_idx
    };
  };

  //-----------------------------------------------------------------------------------------------------------
  /* TAINT use proper parsing tool */
  this.parse_merge_quadref = function(merge_quadref) {
    var _, match, q1col, q1idx, q1row, q2col, q2idx, q2row, type;
    if ((type = CND.type_of(merge_quadref)) !== 'text') {
      throw new Error(`(MKTS/TABLE 2120) expected a text for merge_quadref, got a ${rpr(type)}`);
    }
    /* TAINT only supports quadrefs `[a1]` thru `[z99]` */
    if ((match = merge_quadref.match(/^\[([a-z])([0-9]{1,2})\]\.\.\[([a-z])([0-9]{1,2})\]$/)) == null) {
      throw new Error(`(MKTS/TABLE 6098) expected a merge-quadref like '[a1]..[d4]', got ${rpr(merge_quadref)}`);
    }
    [_, q1col, q1row, q2col, q2row] = match;
    q1idx = this._idx_from_col_and_row(q1col, q1row);
    q2idx = this._idx_from_col_and_row(q2col, q2row);
    return [/* TAINT validate that q2 is not to the left / top of q1 */ q1idx, q2idx];
  };

  //-----------------------------------------------------------------------------------------------------------
  this.mkts_events_from_table_description = function(me) {
    var R;
    R = [];
    R.push(['tex', '\n\n']);
    R.push(['(', 'code', [], copy(me)]);
    R.push(['.', 'text', rpr(me), copy(me)]);
    R.push([')', 'code', [], copy(me)]);
    R.push(['tex', '\n\n']);
    return R;
  };

}).call(this);

//# sourceMappingURL=mkts-table.js.map
