// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var $, $async, CND, FS, NET, O, PATH, PS, RPC_SERVER, alert, badge, debug, echo, help, info, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '(INTERSHOP/RPC/SECONDARY)';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  FS = require('fs');

  PATH = require('path');

  NET = require('net');

  //...........................................................................................................
  PS = require('pipestreams');

  ({$, $async} = PS);

  //...........................................................................................................
  this.RPC = require('./cxltx-demo');

  //...........................................................................................................
  O = require('./options');

  /* TAINT temporary */
  O.rpc = {};

  O.app = {};

  O.app.name = 'MKTS';

  O.rpc.port = 8910;

  O.rpc.host = '127.0.0.1';

  //-----------------------------------------------------------------------------------------------------------
  this._socket_listen_on_all = function(socket) {
    socket.on('close', function() {
      return help('socket', 'close');
    });
    socket.on('connect', function() {
      return help('socket', 'connect');
    });
    socket.on('data', function() {
      return help('socket', 'data');
    });
    socket.on('drain', function() {
      return help('socket', 'drain');
    });
    socket.on('end', function() {
      return help('socket', 'end');
    });
    socket.on('error', function() {
      return help('socket', 'error');
    });
    socket.on('lookup', function() {
      return help('socket', 'lookup');
    });
    socket.on('timeout', function() {
      return help('socket', 'timeout');
    });
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._server_listen_on_all = function(server) {
    server.on('close', function() {
      return help('server', 'close');
    });
    server.on('connection', function() {
      return help('server', 'connection');
    });
    server.on('error', function() {
      return help('server', 'error');
    });
    server.on('listening', function() {
      return help('server', 'listening');
    });
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.listen = function(handler = null) {
    var server;
    //.........................................................................................................
    server = NET.createServer((socket) => {
      var S, XXX_t0, counts, on_stop, pipeline, source;
      XXX_t0 = Date.now();
      socket.on('error', (error) => {
        return warn(`socket error: ${error.message}`);
      });
      // info '33733', 'yo'
      //.......................................................................................................
      source = PS._nodejs_input_to_pull_source(socket);
      counts = {
        requests: 0,
        rpcs: 0,
        hits: 0,
        fails: 0,
        errors: 0
      };
      S = {socket, counts};
      pipeline = [];
      on_stop = PS.new_event_collector('stop', () => {
        help("socket.end() called");
        socket.end();
        return debug('33844', (Date.now() / XXX_t0) / 1000);
      });
      //.......................................................................................................
      pipeline.push(source);
      pipeline.push(PS.$split());
      // pipeline.push PS.$show()
      // pipeline.push @$show_counts   S
      pipeline.push(this.$dispatch(S));
      // pipeline.push PS.$show()
      pipeline.push($(function(result, send) {
        S.socket.write(result);
        return send(null);
      }));
      pipeline.push(on_stop.add(PS.$drain()));
      //.......................................................................................................
      PS.pull(...pipeline);
      return null;
    });
    //.........................................................................................................
    if (handler == null) {
      handler = () => {
        var family, host, port;
        ({
          address: host,
          port,
          family
        } = server.address());
        return help(`${O.app.name} RPC server listening on ${family} ${host}:${port}`);
      };
    }
    //.........................................................................................................
    // ### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ###
    // try FS.unlinkSync O.rpc.path catch error then warn error
    // server.listen O.rpc.path, handler
    // ### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ###
    server.listen(O.rpc.port, O.rpc.host, handler);
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$show_counts = function(S) {
    return PS.$watch(function(event) {
      S.counts.requests += +1;
      if ((S.counts.requests % 1000) === 0) {
        urge(JSON.stringify(S.counts));
      }
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$dispatch = function(S) {
    return $((line, send) => {
      var error, event, method, parameters;
      try {
        event = JSON.parse(`[${line}]`);
        [method, ...parameters] = event;
      } catch (error1) {
        error = error1;
        throw error;
      }
      //.......................................................................................................
      debug('33733', {method, parameters});
      send(this.do_rpc(S, method, parameters));
      //.......................................................................................................
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.do_rpc = function(S, method_name, parameters) {
    var error, method;
    S.counts.rpcs += +1;
    method = this.RPC[method_name];
    if (method == null) {
      throw new Error(`no such method: ${rpr(method_name)}`);
    }
    try {
      // return @send_error S, "no such method: #{rpr method_name}"
      //.........................................................................................................
      return method.apply(this.RPC, parameters);
    } catch (error1) {
      error = error1;
      S.counts.errors += +1;
      throw error;
    }
    return null;
  };

  //###########################################################################################################
  if (module.parent == null) {
    RPC_SERVER = this;
    RPC_SERVER.listen();
  }

}).call(this);

//# sourceMappingURL=rpc-server.js.map
