// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, UNITS, alert, badge, debug, echo, eq, help, include, info, jr, log, rpr, test, urge, warn, whisper,
    indexOf = [].indexOf;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MKTS/TABLE/UNITS/TESTS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  test = require('guy-test');

  eq = CND.equals;

  jr = JSON.stringify;

  //...........................................................................................................
  UNITS = require('../mkts-table-units');

  //-----------------------------------------------------------------------------------------------------------
  this._prune = function() {
    var name, ref, value;
    ref = this;
    for (name in ref) {
      value = ref[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._main = function() {
    return test(this, {
      'timeout': 30000
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this["UNITS.parse_nonnegative_quantity 1"] = function(T, done) {
    var error, i, len, matcher, probe, probes_and_matchers, result;
    probes_and_matchers = [
      [
        "1mm",
        {
          "value": 1,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        "1.2mm",
        {
          "value": 1.2,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        "0.3\\mktsLineheight",
        {
          "value": 0.3,
          "unit": "\\mktsLineheight",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        "123456.2mm",
        {
          "value": 123456.2,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        "300mm",
        {
          "value": 300,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        " 300mm",
        {
          "value": 300,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        " 300 mm",
        {
          "value": 300,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      [
        " 300 mm   ",
        {
          "value": 300,
          "unit": "mm",
          "~isa": "MKTS/TABLE/quantity"
        }
      ],
      ["0.3",
      null],
      ["-300mm",
      null],
      ["+300mm",
      null]
    ];
//.........................................................................................................
    for (i = 0, len = probes_and_matchers.length; i < len; i++) {
      [probe, matcher] = probes_and_matchers[i];
      try {
        result = UNITS.parse_nonnegative_quantity(probe);
      } catch (error1) {
        error = error1;
        if ((matcher === null) && ((error.message.match(/unable to parse .* as nonnegative quantity/)) != null)) {
          urge('36633', jr([probe, matcher]));
          T.ok(true);
        } else {
          T.fail(`unexpected error for probe ${rpr(probe)}: ${rpr(error.message)}`);
        }
        continue;
      }
      urge('36633', jr([probe, result]));
      T.eq(result, matcher);
    }
    //.........................................................................................................
    return done();
  };

  //###########################################################################################################
  if (module.parent == null) {
    include = ["UNITS.parse_nonnegative_quantity 1"];
    this._prune();
    this._main();
  }

}).call(this);

//# sourceMappingURL=basic.js.map
